version: "3.8"
services:
  backend:
    container_name: backend
    depends_on: [auth]
    volumes:
      - "./backend:/app"
    build:
      context: ./backend
    ports:
      - 8080:8080
    restart: always
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - BACKEND_REDIRECT_URL=http://localhost:3000/api/auth/callback/auth
      - AUTH_SERVER_URL=http://auth:9096
  auth:
    container_name: auth
    volumes:
      - "./auth:/app"
    build:
      context: ./auth
    ports:
      - 9096:9096
    restart: always
    environment:
      - REDIRECT_URL=http://localhost:3000
  frontend:
    container_name: frontend
    depends_on: [backend, auth]
    stdin_open: true
    environment:
      - NEXT_PUBLIC_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - NEXT_PUBLIC_API_URL=http://backend:8080
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_LOGIN_URL=http://localhost:8080/login
      - NEXT_PUBLIC_AUTH_SERVER=http://auth:9096
      - ENVIRONMENT=${ENVIRONMENT}
    build:
      context: ./frontend
      target: runner
      args:
        - NEXT_PUBLIC_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - NEXT_PUBLIC_API_URL=http://backend:8080
        - NEXTAUTH_URL=http://localhost:3000
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - NEXT_PUBLIC_LOGIN_URL=http://localhost:8080/login
        - NEXT_PUBLIC_AUTH_SERVER=http://auth:9096
        - ENVIRONMENT=${ENVIRONMENT}s
    volumes:
      - "./frontend:/app"
    ports:
      - "3000:3000"
    restart: always