version: "3.8"
services:
  backend:
    container_name: backend
    volumes:
      - "./backend:/app"
    build:
      context: ./backend
    ports:
      - 8080:8080
    restart: always
    environment:
      - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
  frontend:
    container_name: frontend
    depends_on: [backend]
    stdin_open: true
    build:
      context: ./frontend
      target: runner
    volumes:
      - "./frontend:/app"
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=$API_URL
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - NEXT_PUBLIC_GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
