version: "3.8"
services:
  backend:
    container_name: backend
    volumes:
      - "./backend:/app"
    build:
      context: ./backend
    ports:
      - 8080:8080
    restart: always
    links:
      - backend
    networks:
      - default
  frontend:
    container_name: frontend
    depends_on: [backend]
    stdin_open: true
    build:
      context: ./frontend
      target: runner
    volumes:
      - "./frontend:/app"
    ports:
      - "3000:3000"
    restart: always
    networks:
      - default
  networks:
    default:
      external:
        name: cloudbuild