version: "3.8"
services:
  backend:
    container_name: backend
    volumes:
      - "./backend:/app"
    build:
      context: ./backend
    ports:
      - 8080:8080
    restart: always
  frontend:
    container_name: frontend
    depends_on: [backend]
    stdin_open: true
    build:
      context: ./frontend
      target: runner
      args:
        - NEXT_PUBLIC_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - NEXT_PUBLIC_API_UR=${API_URL}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    volumes:
      - "./frontend:/app"
    ports:
      - "3000:3000"
    restart: always