version: "3.8"
services:
  backend:
    container_name: backend
    volumes:
      - "./backend:/app"
    build:
      context: ./backend
    ports:
      - 8080:8080
      - 0.0.0.0:8080:8080
    networks:
      - shared-network
  frontend:
    container_name: frontend
    depends_on: [backend]
    stdin_open: true
    build:
      context: ./frontend
      target: runner
    volumes:
      - "./frontend:/app"
    ports:
      - "3000:3000"
    links:
      - "backend:api"
    networks:
      - shared-network
networks:
  shared-network:
    driver: bridge