export const trainerOverlayText = 'TrainerProfileTrainerProfileTrainerProfile'
  + ' inerProfileTrainerProfileTrainerProfileTra'
  + ' fileTrainerProfileTrainerProfileTrainerPro'
  + ' inerProfileTrainerProfileTrainerProfileTra'
  + ' erProfileTrainerProfileTrainerProfileTrain'
  + ' TrainerProfileTrainerProfileTrainerProfile'
  + ' inerProfileTrainerProfileTrainerProfileTra'
  + ' fileTrainerProfileTrainerProfileTrainerPro'
  + ' inerProfileTrainerProfileTrainerProfileTra'
  + ' erProfileTrainerProfileTrainerProfileTrain'
  + ' TrainerProfileTrainerProfileTrainerProfile'
  + ' inerProfileTrainerProfileTrainerProfileTra'
  + ' fileTrainerProfileTrainerProfileTrainerPro'
  + ' inerProfileTrainerProfileTrainerProfileTra'
  + ' erProfileTrainerProfileTrainerProfileTrain'

export const clientOverlayText = 'ClientProfileClientProfileClientProfile'
  + ' entProfileClientProfileClientProfileClie'
  + ' ofileClientProfileClientProfileClientPro'
  + ' ientProfileClientProfileClientProfileCli'
  + ' ntProfileClientProfileClientProfileClien'
  + ' ClientProfileClientProfileClientProfileC'
  + ' ientProfileClientProfileClientProfileCli'
  + ' fileClientProfileClientProfileClientPro'
  + ' ientProfileClientProfileClientProfileCli'
  + ' ntProfileClientProfileClientProfileClien'
  + ' ClientProfileClientProfileClientProfile'
  + ' ientProfileClientProfileClientProfileCli'
  + ' fileClientProfileClientProfileClientPro'
  + ' ientProfileClientProfileClientProfileCli'
  + ' ntProfileClientProfileClientProfileClien'

