version: 2.1
orbs:
  pulumi: pulumi/pulumi@2.1.0
  gcp-cli: circleci/gcp-cli@3.0.1
  go: circleci/go@1.7.3
commands:
  load-env:
    steps:
      - run: echo 'export GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}'
      - run: echo 'export GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}'
      - run: echo 'export NEXT_PUBLIC_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}'
      - run: echo 'export NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}'
      - run: echo 'export NEXT_PUBLIC_CLIENT_ID=${CLIENT_ID}'
      - run: echo 'export NEXT_PUBLIC_CLIENT_SECRET=${CLIENT_SECRET}'
      - run: echo 'export NEXT_PUBLIC_CODE_CHALLENGE=${CODE_CHALLENGE}'
      - run: echo 'export NEXT_PUBLIC_API_URL=${API_URL}'
      - run: echo 'export NEXTAUTH_URL=${NEXTAUTH_URL}'
      - run: echo 'export NEXT_PUBLIC_DOMAIN_URL=${NEXTAUTH_URL}'
      - run: echo 'export NEXTAUTH_SECRET=${NEXTAUTH_SECRET}'
      - run: echo 'export LOGIN_URL=${LOGIN_URL}'
      - run: echo 'export AUTH_SERVER_URL=${AUTH_SERVER_URL}'
      - run: echo 'export MAIL_PASSWORD=${MAIL_PASSWORD}'
  run-go-tests:
    parameters:
      directory:
        type: string
      test_dir:
        type: string
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "~/project/<< parameters.directory >>/go.sum" }}
      - run:
          command: go mod download
          working_directory: ~/project/<< parameters.directory >>
      - save_cache:
          key: dependency-cache-{{ checksum "~/project/<< parameters.directory >>/go.sum" }}
          paths:
            - ./go.mod
          working_directory: ~/project/<< parameters.directory >>
      - run:
          command: go test -p 1
          working_directory: ~/project/<< parameters.directory >><< parameters.test_dir >>
  backend-test:
    steps:
      - run-go-tests:
          directory: backend
          test_dir: /tests
  auth-test:
    steps:
      - run-go-tests:
          directory: auth
          test_dir: /
jobs:
  frontend-test:
    docker:
      - image: node:16
    steps:
      - checkout
      - load-env
      - restore_cache:
          key: dependency-cache-{{ checksum "~/project/frontend/package-lock.json" }}
      - run:
          command: npm install
          working_directory: ~/project/frontend
      - save_cache:
          key: dependency-cache-{{ checksum "~/project/frontend/package-lock.json" }}
          paths:
            - ./node_modules
          working_directory: ~/project/frontend
      - run:
          command: npm run test-ci
          working_directory: ~/project/frontend
  go-test:
    docker:
      - image: cimg/go:1.19
    environment:
      - ENVIRONMENT=DEV
      - NEXTAUTH_URL=http://localhost:3000
      - AUTH_SERVER_URL=http://localhost:9096
    steps:
      - auth-test
      - backend-test
  e2e-test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - load-env
      - checkout
      - setup_remote_docker
      - run: docker volume create --name=postgres-db
      - run: docker volume create --name=auth-db
      - run: docker-compose build
      - run: docker-compose up --abort-on-container-exit --exit-code-from cypress
  deploy:
    executor:
      name: go/default
      tag: '2.00'
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - go/install:
          version: "1.20"
      - run:
          command: go mod download
          working_directory: ~/project/infrastructure
      - run:
          command: go mod tidy
          working_directory: ~/project/infrastructure
      - run: echo $GOOGLE_CREDENTIALS > gcp-credentials.json
      - run: gcloud auth activate-service-account --key-file=gcp-credentials.json --quiet
      - run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - load-env
      - pulumi/login
      - pulumi/refresh:
          stack: jeremiahbrem/homepersonaltrainers.net/home-trainers
          working_directory: ~/project/infrastructure
      - pulumi/update:
          stack: jeremiahbrem/homepersonaltrainers.net/home-trainers
          working_directory: ~/project/infrastructure
      - run: rm gcp-credentials.json
workflows:
  version: 2
  cd:
    jobs:
      - go-test
      - e2e-test  
      - frontend-test
      # - deploy:
      #     requires:
      #       - go-test
      #       - e2e-test
      #       - frontend-test
      #     filters:
      #       branches:
      #         only:
      #           - main
