version: 2.1
orbs:
  pulumi: pulumi/pulumi@2.1.0
  gcp-cli: circleci/gcp-cli@3.0.1
  go: circleci/go@1.7.3
  node: circleci/node@5.1.0
commands:
  load-env:
    steps:
      - run: echo 'export GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}'
      - run: echo 'export GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}'
      - run: echo 'export NEXT_PUBLIC_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}'
      - run: echo 'export NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}'
      - run: echo 'export NEXT_PUBLIC_API_URL=${API_URL}'
      - run: echo 'export NEXTAUTH_URL=${NEXTAUTH_URL}'
      - run: echo 'export NEXTAUTH_SECRET=${NEXTAUTH_SECRET}'
jobs:
  test:
    docker:
      - image: cimg/base:2021.04
    environment:
      - ENVIRONMENT=DEV
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose up -d --build 
      - node/install:
          node-version: '19.8'
      - run: npm install -g wait-on
      - run: sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run: cd ~/project/frontend && wait-on http://localhost:3000 && npx cypress run
      - run: docker-compose down
  deploy:
    executor:
      name: go/default
      tag: '2.00'
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - go/install:
          version: "1.20"
      - run:
          command: go mod download
          working_directory: ~/project/infrastructure
      - run:
          command: go mod tidy
          working_directory: ~/project/infrastructure
      - run: echo $GOOGLE_CREDENTIALS > gcp-credentials.json
      - run: gcloud auth activate-service-account --key-file=gcp-credentials.json --quiet
      - run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - load-env
      - pulumi/login
      - pulumi/refresh:
          stack: jeremiahbrem/homepersonaltrainers.net/dev
          working_directory: ~/project/infrastructure
      - pulumi/update:
          stack: jeremiahbrem/homepersonaltrainers.net/dev
          working_directory: ~/project/infrastructure
      - run: rm gcp-credentials.json
workflows:
  version: 2
  cd:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
