version: 2.1
orbs:
  pulumi: pulumi/pulumi@2.1.0
  gcp-cli: circleci/gcp-cli@3.0.1
  go: circleci/go@1.7.3
commands:
  load-env:
    steps:
      - run: echo 'export GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}'
      - run: echo 'export GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}'
      - run: echo 'export NEXT_PUBLIC_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}'
      - run: echo 'export NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}'
      - run: echo 'export NEXT_PUBLIC_API_URL=${API_URL}'
      - run: echo 'export NEXTAUTH_URL=${NEXTAUTH_URL}'
      - run: echo 'export NEXTAUTH_SECRET=${NEXTAUTH_SECRET}'
jobs:
  build-backend:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - load-env
      - run: docker build backend
  build-frontend:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run: >
          echo 'docker build frontend
            --build-arg NEXT_PUBLIC_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            --build-arg NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            --build-arg NEXT_PUBLIC_API_URL=${API_URL}
            --build-arg NEXTAUTH_URL=${NEXTAUTH_URL}
            --build-arg NEXTAUTH_SECRET=${NEXTAUTH_SECRET}'
  deploy:
    executor:
      name: go/default
      tag: '2.00'
    docker:
      - image: google/cloud-sdk
    environment:
      API_URL: $API_URL
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
    steps:
      - checkout
      - setup_remote_docker
      - go/install:
          version: "1.20"
      - run:
          command: go mod download
          working_directory: ~/project/infrastructure
      - run:
          command: go mod tidy
          working_directory: ~/project/infrastructure
      - run: echo $GOOGLE_CREDENTIALS > gcp-credentials.json
      - run: gcloud auth activate-service-account --key-file=gcp-credentials.json --quiet
      - run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      -load-env
      - pulumi/login
      - pulumi/refresh:
          stack: home-personal-trainers/homepersonaltrainers.net/dev
          working_directory: ~/project/infrastructure
      - pulumi/update:
          stack: home-personal-trainers/homepersonaltrainers.net/dev
          working_directory: ~/project/infrastructure
      - run: rm gcp-credentials.json
workflows:
  version: 2
  cd:
    jobs:
      - build-backend:
          filters:
            branches:
              ignore:
                - main
      - build-frontend:
          filters:
            branches:
              ignore:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
