version: 2.1
orbs:
  pulumi: pulumi/pulumi@2.1.0
  gcp-cli: circleci/gcp-cli@3.0.1
  go: circleci/go@1.7.3
commands:
  load-env:
    steps:
      - run: echo 'export GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}'
      - run: echo 'export GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}'
      - run: echo 'export NEXT_PUBLIC_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}'
      - run: echo 'export NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}'
      - run: echo 'export NEXT_PUBLIC_API_URL=${API_URL}'
      - run: echo 'export NEXTAUTH_URL=${NEXTAUTH_URL}'
      - run: echo 'export NEXTAUTH_SECRET=${NEXTAUTH_SECRET}'
      - run: echo 'export LOGIN_URL=${LOGIN_URL}'
      - run: echo 'export AUTH_SERVER_URL=${AUTH_SERVER_URL}'
jobs:
  frontend-test:
    docker:
      - image: circleci/node:18.10
    steps:
      - checkout
      - run:
          command: sudo npm install -g npm@5
          working_directory: ~/project/frontend
      - restore_cache:
          key: dependency-cache-{{ checksum "~/project/frontend/package-lock.json" }}
      - run:
          command: npm install
          working_directory: ~/project/frontend
      - save_cache:
          key: dependency-cache-{{ checksum "~/project/frontend/package-lock.json" }}
          paths:
            - ./node_modules
          working_directory: ~/project/frontend
      - run:
          command: npm run test-ci
          working_directory: ~/project/frontend
  e2e-test:
    docker:
      - image: cimg/base:2021.04
    environment:
      - ENVIRONMENT=DEV
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose build
      - run: docker-compose up --abort-on-container-exit --exit-code-from cypress
  deploy:
    executor:
      name: go/default
      tag: '2.00'
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - go/install:
          version: "1.20"
      - run:
          command: go mod download
          working_directory: ~/project/infrastructure
      - run:
          command: go mod tidy
          working_directory: ~/project/infrastructure
      - run: echo $GOOGLE_CREDENTIALS > gcp-credentials.json
      - run: gcloud auth activate-service-account --key-file=gcp-credentials.json --quiet
      - run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - load-env
      - pulumi/login
      - pulumi/refresh:
          stack: jeremiahbrem/homepersonaltrainers.net/dev
          working_directory: ~/project/infrastructure
      - pulumi/update:
          stack: jeremiahbrem/homepersonaltrainers.net/dev
          working_directory: ~/project/infrastructure
      - run: rm gcp-credentials.json
workflows:
  version: 2
  cd:
    jobs:
      # - e2e-test
      - frontend-test
      # - deploy:
      #     requires:
      #       - e2e-test
      #     filters:
      #       branches:
      #         only:
      #           - main
