import Layout from '@/components/layout/layout'
import styles from './page.module.css'
import { Metadata } from 'next'
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico'
  }
}

export default function Page() {
  return (
    <Layout>
      <div className={styles.container}>
        <main className={styles.main}>
          <h1 className={styles.title}>
            HomePersonalTrainers.net
          </h1>
          <h2>
            Coming soon...
          </h2>
        </main>
      </div>
    </Layout>
  )
}