import Layout from '@/components/layout/layout'
import styles from './page.module.scss'
import { Metadata } from 'next'
import Image from 'next/image'
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  }
}

export default function Page() {
  return (
    <Layout>
      <div className={styles.container}>
        <main className={styles.main}>
          <h1 className={styles.title}>
            <Image src={'hpt-logo.svg'} alt={'home personal trainer logo'} height={0} width={0} />
            HomePersonalTrainers.net
          </h1>
          <h2>
            Coming soon...
          </h2>
        </main>
      </div>
    </Layout>
  )
}